name:       yesodweb
author:     Michael Snoyman
maintainer: Michael Snoyman
license:    BSD3

default-extensions:
- TemplateHaskell
- QuasiQuotes
- OverloadedStrings
- NoImplicitPrelude
- CPP
- OverloadedStrings
- MultiParamTypeClasses
- TypeFamilies
- GADTs
- GeneralizedNewtypeDeriving
- FlexibleContexts
- PatternGuards
- ViewPatterns

dependencies:
- base >=4 && <5
- yesod >=1.2
- yesod-core >=1.2
- yesod-static >=1.2
- yesod-form >=1.2
- yesod-newsfeed >=1.2
- bytestring >=0.9
- text >=0.11
- template-haskell
- shakespeare
- wai-extra >=2.0
- yaml >=0.8
- blaze-html >=0.7
- conduit >=0.5.2.1
- conduit-extra
- resourcet >=0.3
- xss-sanitize >=0.3.1
- attoparsec >=0.10
- data-default
- xml-conduit >=1.0
- time
- http-types >=0.7
- containers
- simple-sendfile >=0.2.1
- unix
- transformers
- process
- pureMD5
- wai-app-static
- markdown
- html-conduit
- classy-prelude
- rio

library:
  source-dirs: src

executables:
  yesodweb:
    main: Main.hs
    source-dirs: app
    dependencies:
    - yesodweb
    when:
    - condition: flag(dev)
      then:
        ghc-options:
        - -Wall
        - -threaded
        - -O0
        cpp-options: -DDEVELOPMENT
      else:
        ghc-options:
        - -Wall
        - -threaded
        - -O2
flags:
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
