apiVersion: v1
kind: ReplicationController
metadata:
    name: yesodweb
    labels:
        app: yesodweb
spec:
  replicas: 1
  template:
    metadata:
        labels:
            app: yesodweb
    spec:
        containers:
        - name: yesodweb
          image: snoyberg/yesodweb:latest
          command: ["yesodweb", "development"]
          workingDir: /app
          ports:
          - name: http
            containerPort: 3001
          env:
          - name: PORT
            value: "3001"
