apiVersion: v1
kind: Service
metadata:
    name: yesodweb
    labels:
        app: yesodweb
spec:
    type: LoadBalancer
    ports:
    - name: http
      port: 80
      targetPort: http
    selector:
        app: yesodweb
